import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

from mcp.server.fastmcp import FastMCP

PROJECT_ROOT = Path(__file__).parent
WORKSPACE = PROJECT_ROOT / "workspace"
WORKSPACE.mkdir(exist_ok=True)

mcp = FastMCP("video-analytics")


@mcp.tool()
def get_current_task() -> str:
    """Read the current video analysis task generated by the Gemini planner.
    Returns the full execution plan, reasoning, and the coding prompt
    that should be used to write the solution script."""
    task_file = WORKSPACE / "current_task.json"
    if not task_file.exists():
        return json.dumps({"error": "No current task. Run main.py first."})
    task = json.loads(task_file.read_text())
    return json.dumps(task, indent=2)


@mcp.tool()
def get_toolbox_reference() -> str:
    """Return the full toolbox reference (available models and tools)
    so the code agent knows what imports and APIs are available."""
    sys.path.insert(0, str(PROJECT_ROOT))
    from main import ToolboxRegistry
    return ToolboxRegistry.build_toolbox_description()


@mcp.tool()
def write_solution(python_code: str, filename: str = "solution.py") -> str:
    """Write a Python script to the workspace directory.
    This is the code that will be executed against the video frames."""
    script_path = WORKSPACE / filename
    script_path.write_text(python_code)
    return json.dumps({
        "status": "written",
        "path": str(script_path),
        "lines": len(python_code.splitlines()),
    })


@mcp.tool()
def execute_solution(filename: str = "solution.py",
                     frames_dir: Optional[str] = None,
                     timeout: int = 120) -> str:
    """Execute a solution script from the workspace.
    Passes frames_dir as sys.argv[1] to the script.
    Returns stdout, stderr, and exit code."""
    script_path = WORKSPACE / filename
    if not script_path.exists():
        return json.dumps({"error": f"{filename} not found in workspace."})

    if frames_dir is None:
        task_file = WORKSPACE / "current_task.json"
        if task_file.exists():
            task = json.loads(task_file.read_text())
            frames_dir = task.get("frames_dir", "")

    cmd = [sys.executable, str(script_path)]
    if frames_dir:
        cmd.append(frames_dir)

    start = time.time()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(PROJECT_ROOT),
        )
        elapsed = round(time.time() - start, 2)
        return json.dumps({
            "exit_code": result.returncode,
            "stdout": result.stdout[-4000:] if len(result.stdout) > 4000 else result.stdout,
            "stderr": result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr,
            "elapsed_seconds": elapsed,
            "script": str(script_path),
        })
    except subprocess.TimeoutExpired:
        return json.dumps({"error": f"Script timed out after {timeout}s."})


@mcp.tool()
def get_results() -> str:
    """List all result files produced in the workspace after execution.
    Returns paths to images, JSONs, and text files in workspace/."""
    results = {}
    for ext in ["*.jpg", "*.png", "*.json", "*.txt", "*.csv"]:
        for f in WORKSPACE.glob(ext):
            if f.name == "current_task.json":
                continue
            stat = f.stat()
            results[f.name] = {
                "path": str(f),
                "size_bytes": stat.st_size,
                "modified": time.ctime(stat.st_mtime),
            }
    return json.dumps(results, indent=2)


@mcp.tool()
def run_video_task(cursor_prompt: str, frames_dir: str) -> str:
    """End-to-end: receive a coding prompt from the Gemini planner,
    write it as the current task, and return instructions for the
    code agent to build and execute the solution.

    This is the primary tool called after main.py generates the plan."""
    task = {
        "cursor_prompt": cursor_prompt,
        "frames_dir": frames_dir,
        "instruction": (
            "Write a complete Python script in workspace/solution.py that implements "
            "the cursor_prompt above. Use the toolbox imports "
            "(from toolbox.models.*, from toolbox.tools.*). "
            "The script must accept frames_dir as sys.argv[1]. "
            "After writing, execute it using execute_solution()."
        ),
    }
    task_file = WORKSPACE / "current_task.json"
    task_file.write_text(json.dumps(task, indent=2))
    return json.dumps(task, indent=2)


if __name__ == "__main__":
    mcp.run(transport="stdio")
